###
# Gives Current Balance of the address and the number of tx
GET https://blockchain.info/balance?active=bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h

###
# Give Transactions for multiple addresses 
# each address contains addresses with total recieved, total sent and final balance per address 
# transactions with input and out blocks
# Optional limit parameter to show n transactions e.g. &n=50 (Default: 50, Max: 100)
# Optional offset parameter to skip the first n transactions e.g. &offset=100 (Page 2 for limit 50)
GET https://blockchain.info/multiaddr?active=3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd|bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h

### single address end point
GET https://blockchain.info/rawaddr/12xQ9k5ousS8MqNsMBqHKtjAtCuKezm2Ju

###
GET http://localhost:8000/api/wallet

###
GET http://localhost:8000/api/address/dbe6913a-7192-49be-b5bf-f6bc4917a2b6

###
POST http://localhost:8000/api/address
content-type: application/json

{
    "address": "bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h",
    "wallet_id": "910cb319-40c0-4a3c-9bd9-81c077a74a1d"
}

###
GET http://localhost:8000/api/transactions/8beae9c6-46f9-49b5-8296-05e2c0e251d9?page=1&per_page=3

###
GET http://localhost:8000/api/health