###
# Gives Current Balance of the address and the number of tx
GET https://blockchain.info/balance?active=bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h

###
# Give Transactions for multiple addresses 
# each address contains addresses with total recieved, total sent and final balance per address 
# transactions with input and out blocks
# Optional limit parameter to show n transactions e.g. &n=50 (Default: 50, Max: 100)
# Optional offset parameter to skip the first n transactions e.g. &offset=100 (Page 2 for limit 50)
GET https://blockchain.info/multiaddr?active=3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd|bc1q0sg9rdst255gtldsmcf8rk0764avqy2h2ksqs5

### single address end point
GET https://blockchain.info/rawaddr/12xQ9k5ousS8MqNsMBqHKtjAtCuKezm2Ju


###
GET http://localhost:5000/api/address

###
POST http://localhost:5000/api/address
content-type: application/json

{
    "address": "12xQ9k5ousS8MqNsMBqHKtjAtCuKezm2Ju",
    "wallet_id": "3ac7d4eb-702d-44a7-af43-92cbbc4bc92b"
}

###
user

id
firstname
lastname
email
password

wallet 

user-id
id 
wallet

addresses

id
address-id
wallet-id
curr_balance 

tx

id
address-id
from [{
    address: string,
    value: float
}]
to [{
    address: string,
    value: float
}]
tx_seq bigint
fee float
result float
balance float
timestamp epoch





