###
# Gives Current Balance of the address and the number of tx
GET https://blockchain.info/balance?active=12xQ9k5ousS8MqNsMBqHKtjAtCuKezm2Ju

###
# Give Transactions for multiple addresses 
# each address contains addresses with total recieved, total sent and final balance per address 
# transactions with input and out blocks
# Optional limit parameter to show n transactions e.g. &n=50 (Default: 50, Max: 100)
# Optional offset parameter to skip the first n transactions e.g. &offset=100 (Page 2 for limit 50)
GET https://blockchain.info/multiaddr?active=3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd|bc1q0sg9rdst255gtldsmcf8rk0764avqy2h2ksqs5

### single address end point
GET https://blockchain.info/rawaddr/12xQ9k5ousS8MqNsMBqHKtjAtCuKezm2Ju

###
GET http://localhost:8000/api/wallet

###
GET http://localhost:8000/api/address/8a538656-785a-46b2-bf8f-02f4e0cc89ae

###
POST http://localhost:8000/api/address
content-type: application/json

{
    "address": "bc1q0sg9rdst255gtldsmcf8rk0764avqy2h2ksqs5",
    "wallet_id": "78c4f483-b7e1-44ec-bc03-33322549f393"
}

###
GET http://localhost:8000/api/transactions/ec87b7b1-6c7f-4c7d-9b0c-141cb9456e6d?page=1&per_page=20